function AddTextEntry(key, value)
    Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
    end
    
    Citizen.CreateThread(function()
    AddTextEntry('124spider', 'Fiat Spider')
    AddTextEntry('rs615', 'rs615')
    AddTextEntry('16challenger', 'Dodge Challenger')
    AddTextEntry('sian', 'Sian')
    AddTextEntry('18performante', 'Lamborghini Performante')
    AddTextEntry('21camaro', 'Camaro 2021')
    AddTextEntry('x6m', 'X6 M')       
    AddTextEntry('18velar', 'Range Rover Velar')    
    AddTextEntry('19gt500', 'Ford GT500')   
    AddTextEntry('g65amg', 'G65 AMG') 
    AddTextEntry('19s650', 'Mercedes S650')    
    AddTextEntry('2019chiron', 'Bugatti Chiron')    
    AddTextEntry('2020exc', 'Sanchez')    
    AddTextEntry('20xmax', 'Xmax')    
    AddTextEntry('370z', 'Nissan 370z')    
    AddTextEntry('4881', 'Ferrari 488')    
    AddTextEntry('4c', 'Alfa Romeo 4c')    
    AddTextEntry('599xxevo', 'Ferrari 599XXEVO')    
    AddTextEntry('63lb', 'Mercedes C63LB')    
    AddTextEntry('718boxster', 'Porsche 718')    
    AddTextEntry('720s', 'Mclaren 720s')    
    AddTextEntry('911r', 'Porsche 911')    
    AddTextEntry('992t', 'Porsche 992')    
    AddTextEntry('a45amg', 'Mercedes A45')    
    AddTextEntry('a80', 'Toyota Supra')    
    AddTextEntry('a8audi', 'Audi A8')    
    AddTextEntry('amggtr', 'Mercedes AMG GTR')    
    AddTextEntry('argiu', 'Alfa Romeo Argiu')    
    AddTextEntry('ast', 'Aston Martin Superleggera')    
    AddTextEntry('bmwe65', 'BMW 750Li')    
    AddTextEntry('bmwm8', 'BMW M8')    
    AddTextEntry('boss429', 'Ford Boss')    
    AddTextEntry('brabus850', 'Brabus 850')    
    AddTextEntry('brz', 'Subaru BRZ')   
    AddTextEntry('c7', 'Corvette C7')   
    AddTextEntry('c8', 'Corvette C8')       
    AddTextEntry('cb500f', 'CB500F')   
    AddTextEntry('ccx', 'Koenigsegg CCX')   
    AddTextEntry('celisupra', 'SupraOld')   
    AddTextEntry('cls63s', 'Mercedes CLS63S')   
    AddTextEntry('contss18', 'Bentley Continental')   
    AddTextEntry('corsae', 'Opel Corsa')   
    AddTextEntry('db11', 'Aston Martin DB11')   
    AddTextEntry('divo', 'Bugatti Divo')   
    AddTextEntry('e63w213', 'Mercedes C63S')   
    AddTextEntry('er34', 'Nissan Skyline')   
    AddTextEntry('exige12', 'Lotus Exige')   
    AddTextEntry('f12m', 'Ferrari F12M')   
    AddTextEntry('f150', 'Ford F150')   
    AddTextEntry('f812', 'Ferrari 812')   
    AddTextEntry('fd', 'Mazda RX7')   
    AddTextEntry('fiat500', 'Fiat500')   
    AddTextEntry('fm488', '488 Special')   
    AddTextEntry('ftype', 'Jaguar F Type')   
    AddTextEntry('g63', 'Mercedes G63')   
    AddTextEntry('giulia', 'Alfa Romeo Giulia')   
    AddTextEntry('goldwing', 'Goldwing')   
    AddTextEntry('grandgt18', 'Porsche Grand GT')   
    AddTextEntry('gt17', 'Ford GT')   
    AddTextEntry('gt2rsmr', 'Porsche GT2 RS')   
    AddTextEntry('gt63samg', 'Mercedes GT63S')   
    AddTextEntry('gt86', 'Mazda GT')   
    AddTextEntry('hondacivictr', 'Honda Civic')   
    AddTextEntry('huayra', 'Pagani Huayra')   
    AddTextEntry('hvrod', 'Harley HVROD')   
    AddTextEntry('i8', 'BMW I8')   
    AddTextEntry('ipace', 'Jaguar E Pace')   
    AddTextEntry('lp610', 'Lamborghini Hurucan LP610')   
    AddTextEntry('m2', 'BMW M2')   
    AddTextEntry('m5f90', 'BMW M5')   
    AddTextEntry('m6f13', 'M6')   
    AddTextEntry('mb300si', 'Mercedes MB300')   
    AddTextEntry('mbgle', 'Mercedes GLE450')   
    AddTextEntry('mgrantur2010', 'Maserati Grantur')   
    AddTextEntry('mk1rabbit', 'Volkswagen Rabbit')   
    AddTextEntry('models', 'Tesla Model S')   
    AddTextEntry('monza', 'Ferrari Monza')   
    AddTextEntry('mustang19', 'Ford Mustang')   
    AddTextEntry('mxpan', 'Mazda MX5')   
    AddTextEntry('p1', 'Mclaren P1')   
    AddTextEntry('corsae', 'Opel Corsa')  
    AddTextEntry('p7', 'Jaguar P7')   
    AddTextEntry('panamera17turbo', 'Porsche Panamera')   
    AddTextEntry('passatr', 'Volkswagen Passat')   
    AddTextEntry('pcs18', 'Porsche Cayenne')   
    AddTextEntry('pd458wb', 'Ferrari 458')   
    AddTextEntry('polo2018', 'Volkswagen Polo')   
    AddTextEntry('pturismo', 'Porsche Turismo')   
    AddTextEntry('r8prior', 'Audi R8')   
    AddTextEntry('ram2500', 'Dodge Ram 2500')   
    AddTextEntry('rmodm4gts', 'BMW M4')   
    AddTextEntry('rrst', 'Range Rover Sport')   
    AddTextEntry('rs318', 'Audi RS3')   
    AddTextEntry('rs5r', 'Audi RS5')   
    AddTextEntry('rs6', 'Audi RS6')   
    AddTextEntry('rx8r', 'Mazda RX8')   
    AddTextEntry('s3sedan', 'Audi S3')   
    AddTextEntry('s500w222', 'Mercedes S500')   
    AddTextEntry('s60pole', 'Volvo S60')   
    AddTextEntry('sc18', 'Lamborghini SC18')   
    AddTextEntry('subwrx', 'Subaru WRX')   
    AddTextEntry('superb', 'Skoda Superb')   
    AddTextEntry('svj', 'Lamborghini SVJ')   
    AddTextEntry('taycan', 'Porsche Taycan')   
    AddTextEntry('teslax', 'Tesla Model X')   
    AddTextEntry('tr22', 'Tesla Roadster')   
    AddTextEntry('trhawk', 'Jeep Trackhawk')   
    AddTextEntry('urus', 'Lamborghini Urus')   
    AddTextEntry('v250', 'Mercedes Vito V250')   
    AddTextEntry('xkgt', 'Jaguar RSGT')   
    AddTextEntry('z4bmw', 'BMW Z4')   
    AddTextEntry('zl12017', 'Chevrolet ZL1')
    AddTextEntry('s3sedan', 'Audi A3')
    AddTextEntry('4c', 'Alfa Romeo 4C')
    AddTextEntry('argiu', 'Alfa Romeo Argio')
    AddTextEntry('db11', 'Aston Martin DB11')
    AddTextEntry('16challenger', 'Dodge Challenger')
    AddTextEntry('zl12017', 'Camaro Chevrolet ZL12017')
    AddTextEntry('z4bmw', 'BMW M48I')
    AddTextEntry('f812', 'Ferrari 812 Superfast')
    AddTextEntry('rs62', 'Audi RS6')
    AddTextEntry('tempestax', 'Tempesta X')
    AddTextEntry('124spider', 'Fiat Spider')
    AddTextEntry('16challenger', 'Dodge Challenger')
    AddTextEntry('18velar', 'Range Rover Velar')    
    AddTextEntry('19gt500', 'Ford GT500')    
    AddTextEntry('19s650', 'Mercedes S650')    
    AddTextEntry('2019chiron', 'Bugatti Chiron')    
    AddTextEntry('2020exc', 'Sanchez')    
    AddTextEntry('20xmax', 'Xmax')    
    AddTextEntry('370z', 'Nissan 370z')      
    AddTextEntry('4c', 'Alfa Romeo 4c')    
    AddTextEntry('599xxevo', 'Ferrari 599XXEVO')    
    AddTextEntry('63lb', 'Mercedes C63LB')    
    AddTextEntry('718boxster', 'Porsche 718')    
    AddTextEntry('720s', 'Mclaren 720s')    
    AddTextEntry('911r', 'Porsche 911')    
    AddTextEntry('992t', 'Porsche 992')    
    AddTextEntry('a45amg', 'Mercedes A45')    
    AddTextEntry('a80', 'Toyota Supra')    
    AddTextEntry('a8audi', 'Audi A8')    
    AddTextEntry('amggtr', 'Mercedes AMG GTR')    
    AddTextEntry('argiu', 'Alfa Romeo Argiu')    
    AddTextEntry('ast', 'Aston Martin Superleggera')    
    AddTextEntry('bmwe65', 'BMW 750Li')    
    AddTextEntry('bmwm8', 'BMW M8')    
    AddTextEntry('boss429', 'Ford Boss')    
    AddTextEntry('brabus850', 'Brabus 850')    
    AddTextEntry('brz', 'Subaru BRZ')   
    AddTextEntry('c7', 'Corvette C7')   
    AddTextEntry('c8', 'Corvette C8')       
    AddTextEntry('cb500f', 'CB500F')   
    AddTextEntry('ccx', 'Koenigsegg CCX')   
    AddTextEntry('celisupra', 'SupraOld')   
    AddTextEntry('cls63s', 'Mercedes CLS63S')   
    AddTextEntry('contss18', 'Bentley Continental')   
    AddTextEntry('db11', 'Aston Martin DB11')   
    AddTextEntry('divo', 'Bugatti Divo')   
    AddTextEntry('e63w213', 'Mercedes C63S')   
    AddTextEntry('er34', 'Nissan Skyline')   
    AddTextEntry('exige12', 'Lotus Exige')   
    AddTextEntry('f12m', 'Ferrari F12M')   
    AddTextEntry('f150', 'Ford F150')   
    AddTextEntry('f812', 'Ferrari 812')   
    AddTextEntry('fd', 'Mazda RX7')   
    AddTextEntry('fiat500', 'Fiat500')     
    AddTextEntry('ftype', 'Jaguar F Type')   
    AddTextEntry('g63', 'Mercedes G63')   
    AddTextEntry('giulia', 'Alfa Romeo Giulia')   
    AddTextEntry('goldwing', 'Goldwing')   
    AddTextEntry('grandgt18', 'Porsche Grand GT')   
    AddTextEntry('gt17', 'Ford GT')   
    AddTextEntry('gt2rsmr', 'Porsche GT2 RS')   
    AddTextEntry('gt63samg', 'Mercedes GT63S')   
    AddTextEntry('gt86', 'Mazda GT')   
    AddTextEntry('hondacivictr', 'Honda Civic')   
    AddTextEntry('huayra', 'Pagani Huayra')   
    AddTextEntry('hvrod', 'Harley HVROD')    
    AddTextEntry('ipace', 'Jaguar E Pace')   
    AddTextEntry('lp610', 'Lamborghini Hurucan LP610')   
    AddTextEntry('m2', 'BMW M2')   
    AddTextEntry('m5f90', 'BMW M5')   
    AddTextEntry('m6f13', 'M6')   
    AddTextEntry('mb300si', 'Mercedes MB300')   
    AddTextEntry('mbgle', 'Mercedes GLE450')   
    AddTextEntry('mgrantur2010', 'Maserati Grantur')   
    AddTextEntry('mk1rabbit', 'Volkswagen Rabbit')   
    AddTextEntry('models', 'Tesla Model S')   
    AddTextEntry('monza', 'Ferrari Monza')   
    AddTextEntry('mustang19', 'Ford Mustang')   
    AddTextEntry('mxpan', 'Mazda MX5')   
    AddTextEntry('nissantitan17', 'Nissan Titan')   
    AddTextEntry('p1', 'Mclaren P1')   
    AddTextEntry('p7', 'Jaguar P7')   
    AddTextEntry('panamera17turbo', 'Porsche Panamera')   
    AddTextEntry('passatr', 'Volkswagen Passat')   
    AddTextEntry('pcs18', 'Porsche Cayenne')   
    AddTextEntry('pd458wb', 'Ferrari 458')   
    AddTextEntry('polo2018', 'Volkswagen Polo')   
    AddTextEntry('pturismo', 'Porsche Turismo')   
    AddTextEntry('r8prior', 'Audi R8')   
    AddTextEntry('ram2500', 'Dodge Ram 2500')   
    AddTextEntry('rmodm4gts', 'BMW M4')   
    AddTextEntry('rrst', 'Range Rover Sport')   
    AddTextEntry('rs318', 'Audi RS3')   
    AddTextEntry('rs5r', 'Audi RS5')   
    AddTextEntry('rs6', 'Audi RS6')   
    AddTextEntry('rx8r', 'Mazda RX8')   
    AddTextEntry('s3sedan', 'Audi S3')   
    AddTextEntry('s500w222', 'Mercedes S500')   
    AddTextEntry('s60pole', 'Volvo S60')   
    AddTextEntry('sc18', 'Lamborghini SC18')   
    AddTextEntry('subwrx', 'Subaru WRX')   
    AddTextEntry('superb', 'Skoda Superb')   
    AddTextEntry('svj', 'Lamborghini SVJ')   
    AddTextEntry('taycan', 'Porsche Taycan')   
    AddTextEntry('teslax', 'Tesla Model X')   
    AddTextEntry('tr22', 'Tesla Roadster')   
    AddTextEntry('trhawk', 'Jeep Trackhawk')   
    AddTextEntry('urus', 'Lamborghini Urus')   
    AddTextEntry('v250', 'Mercedes Vito V250')   
    AddTextEntry('xkgt', 'Jaguar RSGT')   
    AddTextEntry('z4bmw', 'BMW Z4')   
    AddTextEntry('zl12017', 'Chevrolet ZL1')
    AddTextEntry('20r1', 'Yamaha YZF-R1')
    AddTextEntry('bmws', 'BMW S1000RR')
    AddTextEntry('c63s', 'Mercedes C63S')
    AddTextEntry('d99', 'Ducati 1199 Panigale')
    AddTextEntry('daemon', 'Harley Davidson Knucklehead')
    AddTextEntry('kx450f', 'Kawasaki KX450F')
    AddTextEntry('nh2r', 'Kawasaki Ninja H2R')
    AddTextEntry('r6', 'Yamaha YZF-R6')
    AddTextEntry('v4sp', 'Ducati V4 Speciale')
    AddTextEntry('20r1', 'Yamaha YZF-R1')
    AddTextEntry('bmws', 'BMW S1000RR')
    AddTextEntry('c63s', 'Mercedes C63S')
    AddTextEntry('d99', 'Ducati 1199 Panigale')
    AddTextEntry('daemon', 'Harley Davidson Knucklehead')
    AddTextEntry('kx450f', 'Kawasaki KX450F')
    AddTextEntry('nh2r', 'Kawasaki Ninja H2R')
    AddTextEntry('r6', 'Yamaha YZF-R6')
    AddTextEntry('v4sp', 'Ducati V4 Speciale') 
    AddTextEntry('sennas', 'Mclaren Senna')-- sennas
       

    end)